### ISSUE TITLE
V1.4.0 not compatible with sphinx<1.6.0 when build warnings occur

### ISSUE THREAD

**Issue by SteinHeselmans** [melexis/sphinx-traceability-extension#5]
When the traceability plugin should give build warnings about broken links, or missing items, and using traceability==1.4.0 and sphinx<1.6.0, an error occurs:

```
Exception occurred:
  File "/usr/local/lib/python2.7/dist-packages/sphinx/environment/__init__.py", line 341, in doc2path
    docname = docname.replace(SEP, path.sep)
AttributeError: 'tuple' object has no attribute 'replace'
```

Problem is in introduced in #3.
